# NOTE: This data is not correct, it is based on the AMZ driverless car

inertia:
  m:        300.0   # Weight of the Vehicle [kg]
  g:        9.81    # Gravity force         [m/s^2]
  I_z:      165.99     # Inertial force I_zz

kinematics:
  l: 1.53           # Vehicle Length [m]
  b_F: 0.765         # From COG to front axle [m]
  b_R: 0.765        # From COG to rear axle [m]
  w_front: 0.5      # Percentage of weight front
  axle_width: 1.2

tire:
  tire_coefficient: 1.0
  B: 12.56
  C: -1.38
  D: 0.8
  E: -0.58
  radius: 0.2525

aero:
  C_Down: 0.0 # F_Downforce = C_Downforce*v_x^2
  C_drag: 1 # F_Drag = C_Drag*v_x^2

input_ranges:
  acceleration:
    max: 5.2
    min: -5.2
  velocity:
    max: 30
    min: 0
  steering:
    max: 0.42
    min: -0.42
